version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        token:
        TZ: Europe/Helsinki
        digitransitApiKey:
    container_name: tg-feedbot
    image: ainki/tg-poikkeusinfo:latest
    restart: always
    volumes:
      - ./data:/app/data