version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        token: 
        TZ: Europe/Helsinki
        digitransitApiKey: 
        channelId: 
    container_name: tg-poikkeusinfo
    image: ainki/tg-poikkeusinfo:latest
    restart: always
    volumes:
      - ./data:/app/data